WITH CTE_1 AS (
SELECT 
(CASE WHEN DIMENSIONS_DOI IS NOT NULL THEN DIMENSIONS_DOI 
					 WHEN SCOPUS_DOI IS NOT NULL THEN SCOPUS_DOI 
					 WHEN WOS_DOI IS NOT NULL THEN WOS_DOI 
					 WHEN ALEX_DOI IS NOT NULL THEN ALEX_DOI
					 END) AS PUB_DOI, DIMENSIONS_COUNTRY, SCOPUS_COUNTRY, WOS_COUNTRY, ALEX_COUNTRY,
					CASE WHEN DIMENSIONS_DOI IS NOT NULL THEN 1 ELSE 0 END AS DIMENSIONS_DOI,
					CASE WHEN SCOPUS_DOI IS NOT NULL THEN 1 ELSE 0 END AS SCOPUS_DOI,
					CASE WHEN WOS_DOI IS NOT NULL THEN 1 ELSE 0 END AS WOS_DOI,
					CASE WHEN ALEX_DOI IS NOT NULL THEN 1 ELSE 0 END AS ALEX_DOI	
FROM [userdb_hayatdavoudij].[dbo].[t3]
)
, CTE_2 AS (
SELECT PUB_DOI, DIMENSIONS_DOI, SCOPUS_DOI, WOS_DOI, ALEX_DOI,
		(CASE WHEN DIMENSIONS_COUNTRY IS NOT NULL THEN DIMENSIONS_COUNTRY
			  WHEN SCOPUS_COUNTRY IS NOT NULL THEN SCOPUS_COUNTRY
			  WHEN WOS_COUNTRY IS NOT NULL THEN WOS_COUNTRY
			  WHEN ALEX_COUNTRY IS NOT NULL THEN ALEX_COUNTRY
			  END) AS COUNTRY
FROM CTE_1
)
--4565303

--BLOCK 2 REMOVES THE DUPLICATES

SELECT  
        [PUB_DOI], COUNTRY,
        MAX([DIMENSIONS_DOI]) AS [DIMENSIONS_DOI],
        MAX([SCOPUS_DOI]) AS [SCOPUS_DOI],
        MAX([WOS_DOI]) AS [WOS_DOI],
        MAX([ALEX_DOI]) AS [ALEX_DOI]
    INTO userdb_hayatdavoudij.dbo.t4_main   
    FROM CTE_2
    GROUP BY [PUB_DOI], COUNTRY
   

--3901376